import cv2
image = cv2.imread("image.jpg")
high = cv2.resize(image, (600, 600))
medium = cv2.resize(image, (300, 300))
low = cv2.resize(image, (100, 100))
cv2.imshow("Original", image)
cv2.imshow("High Sampling", high)
cv2.imshow("Medium Sampling", medium)
cv2.imshow("Low Sampling", low)
cv2.waitKey(0)
cv2.destroyAllWindows()